// <auto-generated />
using System;
using EntertainmentWebApiApplication.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntertainmentWebApiApplication.Migrations
{
    [DbContext(typeof(EntertainmentDataContext))]
    partial class EntertainmentDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntertainmentWebApiApplication.Infrastructure.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("LastUpdatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordCreatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamA_Id")
                        .HasColumnType("int");

                    b.Property<int>("TeamA_Score")
                        .HasColumnType("int");

                    b.Property<int?>("TeamB_Id")
                        .HasColumnType("int");

                    b.Property<int>("TeamB_Score")
                        .HasColumnType("int");

                    b.Property<int?>("Winner_Id")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("TeamA_Id");

                    b.HasIndex("TeamB_Id");

                    b.HasIndex("Winner_Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("EntertainmentWebApiApplication.Infrastructure.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedDttm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("EntertainmentWebApiApplication.Infrastructure.Models.Match", b =>
                {
                    b.HasOne("EntertainmentWebApiApplication.Infrastructure.Models.Team", "TeamA_Obj")
                        .WithMany()
                        .HasForeignKey("TeamA_Id");

                    b.HasOne("EntertainmentWebApiApplication.Infrastructure.Models.Team", "TeamB_Obj")
                        .WithMany()
                        .HasForeignKey("TeamB_Id");

                    b.HasOne("EntertainmentWebApiApplication.Infrastructure.Models.Team", "Winner_Obj")
                        .WithMany()
                        .HasForeignKey("Winner_Id");

                    b.Navigation("TeamA_Obj");

                    b.Navigation("TeamB_Obj");

                    b.Navigation("Winner_Obj");
                });
#pragma warning restore 612, 618
        }
    }
}
